"""initial schema

Revision ID: 30c6574b6cb0
Revises: 
Create Date: 2026-08-04 16:28:53.041487

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '30c6574b6cb0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('attendants',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('pin_hash', sa.String(length=255), nullable=False),
    sa.Column('shop_role', sa.Enum('attendant', 'owner', name='shoprole'), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('products',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('category', sa.Enum('produce', 'dry', 'packaging', name='category'), nullable=False),
    sa.Column('base_unit', sa.Enum('kg', 'piece', 'litre', name='baseunit'), nullable=False),
    sa.Column('avg_piece_weight', sa.Float(), nullable=True),
    sa.Column('current_cost_per_unit', sa.Float(), nullable=True),
    sa.Column('reorder_threshold', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('stock_batches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('bulk_quantity', sa.Float(), nullable=False),
    sa.Column('bulk_unit', sa.String(length=50), nullable=False),
    sa.Column('total_cost', sa.Float(), nullable=False),
    sa.Column('cost_per_base_unit', sa.Float(), nullable=False),
    sa.Column('quantity_remaining', sa.Float(), nullable=False),
    sa.Column('date_received', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.Enum('open', 'closed', name='batchstatus'), nullable=False),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('stock_batches', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_stock_batches_product_id'), ['product_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_stock_batches_status'), ['status'], unique=False)

    op.create_table('sales',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_uuid', sa.String(length=64), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('batch_id', sa.Integer(), nullable=False),
    sa.Column('attendant_id', sa.Integer(), nullable=False),
    sa.Column('quantity_sold', sa.Float(), nullable=False),
    sa.Column('unit_sold_in', sa.String(length=20), nullable=False),
    sa.Column('price_charged', sa.Float(), nullable=False),
    sa.Column('cost_at_sale', sa.Float(), nullable=False),
    sa.Column('profit', sa.Float(), nullable=False),
    sa.Column('sync_status', sa.Enum('pending', 'synced', name='syncstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('synced_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['attendant_id'], ['attendants.id'], ),
    sa.ForeignKeyConstraint(['batch_id'], ['stock_batches.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('sales', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sales_attendant_id'), ['attendant_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_sales_client_uuid'), ['client_uuid'], unique=True)
        batch_op.create_index(batch_op.f('ix_sales_product_id'), ['product_id'], unique=False)

    op.create_table('wastage',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('batch_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Float(), nullable=False),
    sa.Column('reason', sa.Enum('spoilage', 'damage', 'other', name='wastagereason'), nullable=False),
    sa.Column('date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('recorded_by', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['batch_id'], ['stock_batches.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['recorded_by'], ['attendants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('wastage', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_wastage_product_id'), ['product_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('wastage', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_wastage_product_id'))

    op.drop_table('wastage')
    with op.batch_alter_table('sales', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sales_product_id'))
        batch_op.drop_index(batch_op.f('ix_sales_client_uuid'))
        batch_op.drop_index(batch_op.f('ix_sales_attendant_id'))

    op.drop_table('sales')
    with op.batch_alter_table('stock_batches', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_stock_batches_status'))
        batch_op.drop_index(batch_op.f('ix_stock_batches_product_id'))

    op.drop_table('stock_batches')
    op.drop_table('products')
    op.drop_table('attendants')
    # ### end Alembic commands ###
