"""add voided_at and voided_by to sales

Revision ID: c4d2e3f5a6b7
Revises: b3f1a9c2d8e4
Create Date: 2026-08-04 18:20:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c4d2e3f5a6b7'
down_revision = 'b3f1a9c2d8e4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sales', schema=None) as batch_op:
        batch_op.add_column(sa.Column('voided_at', sa.DateTime(timezone=True), nullable=True))
        batch_op.add_column(sa.Column(
            'voided_by',
            sa.Integer(),
            sa.ForeignKey('attendants.id', name='fk_sales_voided_by_attendants'),
            nullable=True,
        ))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sales', schema=None) as batch_op:
        batch_op.drop_column('voided_by')
        batch_op.drop_column('voided_at')
    # ### end Alembic commands ###
